<a href="https://colab.research.google.com/github/Navyashreecs/Navyashreecs/blob/main/task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.Create 3*3 numpy array with any1 boolean values..........1)
import numpy as np
x=np.array([[7,8,9],[6,5,4],[3,2,1]])
print(x>10)                         #print as false
print(x>0)                          #print as true




[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#2.Create 3*3 matrix with values ranging from 0-8................2)
arr_01=np.arange(0,9).reshape(3,3)
print(arr_01)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3.Create 5*2 integer array from range b/w 100-200,d/f b/w each element is 10..............3)
array_03=np.arange(100,200,10).reshape(5,2)
print(array_03)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [ ]:
#4.Return array of items in 3rd column from all rows.............4)
array_100=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(array_100[:,2])

[33 66 99]


In [ ]:
#5.Return array of odd rows and even columns.................5)
arr_02=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
print(arr_02[::2,1::2])

[[ 6 12]
 [30 36]
 [54 60]]


In [ ]:
#7.Create array as same as below and print the dimension.................6)
array_90=np.array([[['Try','to'],['Create','me']],[['and','also'],['guess my','dimension']]])
print(array_90)
print(array_90.ndim)

[[['Try' 'to']
  ['Create' 'me']]

 [['and' 'also']
  ['guess my' 'dimension']]]
3


In [ ]:
#8.Slicing of array by taking 7th question as hint
print(array_90[0,0,0],array_90[1,0,0])


Try and


In [ ]:
#9.Creating the array and finding it's dim.....................7)
arr_00=np.array([[[[2],[4]],[[6],[8]],[[10],[12]]],[[[14],[16]],[[18],[20]],[[22],[24]]],[[[1],[3]],[[5],[7]],[[9],[11]]],[[[13],[15]],[[17],[19]],[[21],[23]]]])
print(arr_00)
print(arr_00.ndim)

[[[[ 2]
   [ 4]]

  [[ 6]
   [ 8]]

  [[10]
   [12]]]


 [[[14]
   [16]]

  [[18]
   [20]]

  [[22]
   [24]]]


 [[[ 1]
   [ 3]]

  [[ 5]
   [ 7]]

  [[ 9]
   [11]]]


 [[[13]
   [15]]

  [[17]
   [19]]

  [[21]
   [23]]]]
4
